// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrlShortener.Infrastructure.EfCore.Postgres.Context;

#nullable disable

namespace UrlShortener.Infrastructure.EfCore.Postgres.Migrations
{
    [DbContext(typeof(ShortenPostgresDbContext))]
    partial class ShortenPostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrlShortener.Domain.Shorten.Analytics.ShortLinkAccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AccessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("accessed_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("ShortLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("short_link_id");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_short_link_access_logs");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_short_link_access_logs_code");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_short_link_access_logs_id");

                    b.HasIndex("ShortLinkId")
                        .HasDatabaseName("ix_short_link_access_logs_short_link_id");

                    b.ToTable("short_link_access_logs", "shorten");
                });

            modelBuilder.Entity("UrlShortener.Domain.Shorten.ShortLinks.ShortLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsExpiring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_expiring");

                    b.Property<string>("LongUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("long_url");

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("short_url");

                    b.HasKey("Id")
                        .HasName("pk_short_links");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_short_links_code");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_short_links_id");

                    b.ToTable("short_links", "shorten");
                });
#pragma warning restore 612, 618
        }
    }
}
